### ISSUE TITLE
Error: No compatible version found: uglifyjs@'^2.3.6'

### ISSUE THREAD

**Issue by vjeux** [andreypopp/react-quickstart#5]
When running `npm install`

```
npm ERR! Error: No compatible version found: uglifyjs@'^2.3.6'
npm ERR! Valid install targets:
npm ERR! ["2.3.6"]
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:719:10)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:638:10
npm ERR!     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 13.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/vjeux/www/mongo-graphql
npm ERR! node -v v0.10.15
npm ERR! npm -v 1.3.5
```

**Comment by andreypopp** [comment]
@vjeux you need to update your npm to 1.4.x

**Comment by vjeux** [comment]
Thanks will do

**Comment by vjeux** [comment]
```
npm update npm -g
```

so meta :)

**Comment by andreypopp** [comment]
Though I'm fixing this to work with npm 1.3.x. Thanks for the report!
